version: '3.8'

services:
  rosserial:
    build:
      context: .
      dockerfile: rosserial.dockerfile

    privileged: true
    stdin_open: true
    tty: true
    volumes:
      - ../:/root/Arduino/libraries/Hydrus
      - ../catkin_ws:/home/catkin_ws/src/test_rosserial
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"

    environment:
      # - ARDUINO_BOARD=arduino:avr:uno
      - ARDUINO_BOARD=arduino:avr:mega
